
=== Collection

* *objects*: list of <<Histogram>> or <<Ntuple>> or <<ParameterizedFunction>> or <<BinnedEvaluatedFunction>> or <<Collection>> _(default: +[]+)_
* *axis*: list of <<Axis>> _(default: +[]+)_
* *title*: str _(default: +None+)_
* *metadata*: <<Metadata>> _(default: +None+)_
* *decoration*: <<Decoration>> _(default: +None+)_
* *script*: str _(default: +None+)_=== Histogram

* *axis*: list of <<Axis>> with length in _[1, inf)_
* *counts*: <<UnweightedCounts>> or <<WeightedCounts>>
* *profile*: list of <<Profile>> _(default: +[]+)_
* *axis_covariances*: list of <<Covariance>> _(default: +[]+)_
* *profile_covariances*: list of <<Covariance>> _(default: +[]+)_
* *functions*: list of <<ParameterizedFunction>> or <<EvaluatedFunction>> _(default: +[]+)_
* *title*: str _(default: +None+)_
* *metadata*: <<Metadata>> _(default: +None+)_
* *decoration*: <<Decoration>> _(default: +None+)_
* *script*: str _(default: +None+)_=== Axis

* *binning*: <<IntegerBinning>> or <<RegularBinning>> or <<HexagonalBinning>> or <<EdgesBinning>> or <<IrregularBinning>> or <<CategoryBinning>> or <<SparseRegularBinning>> or <<FractionBinning>> or <<PredicateBinning>> or <<VariationBinning>> _(default: +None+)_
* *expression*: str _(default: +None+)_
* *statistics*: <<Statistics>> _(default: +None+)_
* *title*: str _(default: +None+)_
* *metadata*: <<Metadata>> _(default: +None+)_
* *decoration*: <<Decoration>> _(default: +None+)_=== IntegerBinning

* *min*: int in _(-inf, inf)_
* *max*: int in _(-inf, inf)_
* *loc_underflow*: one of BinLocation.{BinLocation.below3, BinLocation.below2, BinLocation.below1, BinLocation.nonexistent, BinLocation.above1, BinLocation.above2, BinLocation.above3} _(default: +BinLocation.nonexistent+)_
* *loc_overflow*: one of BinLocation.{BinLocation.below3, BinLocation.below2, BinLocation.below1, BinLocation.nonexistent, BinLocation.above1, BinLocation.above2, BinLocation.above3} _(default: +BinLocation.nonexistent+)_=== RegularBinning

* *num*: int in _[1, inf)_
* *interval*: <<RealInterval>>
* *overflow*: <<RealOverflow>> _(default: +None+)_
* *circular*: bool _(default: +False+)_=== RealInterval

* *low*: float in _[-inf, inf]_
* *high*: float in _[-inf, inf]_
* *low_inclusive*: bool _(default: +True+)_
* *high_inclusive*: bool _(default: +False+)_=== RealOverflow

* *loc_underflow*: one of BinLocation.{BinLocation.below3, BinLocation.below2, BinLocation.below1, BinLocation.nonexistent, BinLocation.above1, BinLocation.above2, BinLocation.above3} _(default: +BinLocation.nonexistent+)_
* *loc_overflow*: one of BinLocation.{BinLocation.below3, BinLocation.below2, BinLocation.below1, BinLocation.nonexistent, BinLocation.above1, BinLocation.above2, BinLocation.above3} _(default: +BinLocation.nonexistent+)_
* *loc_nanflow*: one of BinLocation.{BinLocation.below3, BinLocation.below2, BinLocation.below1, BinLocation.nonexistent, BinLocation.above1, BinLocation.above2, BinLocation.above3} _(default: +BinLocation.nonexistent+)_
* *minf_mapping*: one of RealOverflow.{RealOverflow.missing, RealOverflow.in_underflow, RealOverflow.in_overflow, RealOverflow.in_nanflow} _(default: +RealOverflow.in_underflow+)_
* *pinf_mapping*: one of RealOverflow.{RealOverflow.missing, RealOverflow.in_underflow, RealOverflow.in_overflow, RealOverflow.in_nanflow} _(default: +RealOverflow.in_overflow+)_
* *nan_mapping*: one of RealOverflow.{RealOverflow.missing, RealOverflow.in_underflow, RealOverflow.in_overflow, RealOverflow.in_nanflow} _(default: +RealOverflow.in_nanflow+)_=== HexagonalBinning

* *qmin*: int in _(-inf, inf)_
* *qmax*: int in _(-inf, inf)_
* *rmin*: int in _(-inf, inf)_
* *rmax*: int in _(-inf, inf)_
* *coordinates*: one of HexagonalBinning.{HexagonalBinning.offset, HexagonalBinning.doubled_offset, HexagonalBinning.cube_xy, HexagonalBinning.cube_yz, HexagonalBinning.cube_xz} _(default: +HexagonalBinning.offset+)_
* *xorigin*: float in _(-inf, inf)_ _(default: +0.0+)_
* *yorigin*: float in _(-inf, inf)_ _(default: +0.0+)_
* *qangle*: float in _[-1.5707963267948966, 1.5707963267948966]_ _(default: +0.0+)_
* *qoverflow*: <<RealOverflow>> _(default: +None+)_
* *roverflow*: <<RealOverflow>> _(default: +None+)_=== EdgesBinning

* *edges*: list of float with length in _[1, inf)_
* *overflow*: <<RealOverflow>> _(default: +None+)_
* *low_inclusive*: bool _(default: +True+)_
* *high_inclusive*: bool _(default: +False+)_
* *circular*: bool _(default: +False+)_=== IrregularBinning

* *intervals*: list of <<RealInterval>> with length in _[1, inf)_
* *overflow*: <<RealOverflow>> _(default: +None+)_
* *overlapping_fill*: one of IrregularBinning.{IrregularBinning.undefined, IrregularBinning.all, IrregularBinning.first, IrregularBinning.last} _(default: +IrregularBinning.undefined+)_=== CategoryBinning

* *categories*: list of str
* *loc_overflow*: one of BinLocation.{BinLocation.below3, BinLocation.below2, BinLocation.below1, BinLocation.nonexistent, BinLocation.above1, BinLocation.above2, BinLocation.above3} _(default: +BinLocation.nonexistent+)_=== SparseRegularBinning

* *bins*: list of int
* *bin_width*: float in _(0, inf]_
* *origin*: float in _[-inf, inf]_ _(default: +0.0+)_
* *overflow*: <<RealOverflow>> _(default: +None+)_
* *low_inclusive*: bool _(default: +True+)_
* *high_inclusive*: bool _(default: +False+)_
* *minbin*: int in _[-9223372036854775808, 9223372036854775807]_ _(default: +-9223372036854775808+)_
* *maxbin*: int in _[-9223372036854775808, 9223372036854775807]_ _(default: +9223372036854775807+)_=== FractionBinning

* *layout*: one of FractionBinning.{FractionBinning.passall, FractionBinning.failall, FractionBinning.passfail} _(default: +FractionBinning.passall+)_
* *layout_reversed*: bool _(default: +False+)_
* *error_method*: one of FractionBinning.{FractionBinning.undefined, FractionBinning.normal, FractionBinning.clopper_pearson, FractionBinning.wilson, FractionBinning.agresti_coull, FractionBinning.feldman_cousins, FractionBinning.jeffrey, FractionBinning.bayesian_uniform} _(default: +FractionBinning.undefined+)_=== PredicateBinning

* *predicates*: list of str with length in _[1, inf)_
* *overlapping_fill*: one of IrregularBinning.{IrregularBinning.undefined, IrregularBinning.all, IrregularBinning.first, IrregularBinning.last} _(default: +IrregularBinning.undefined+)_=== VariationBinning

* *variations*: list of <<Variation>> with length in _[1, inf)_=== Variation

* *assignments*: list of <<Assignment>>
* *systematic*: list of float _(default: +[]+)_
* *category_systematic*: list of str _(default: +[]+)_=== Assignment

* *identifier*: unique str
* *expression*: str=== UnweightedCounts

* *counts*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>>=== WeightedCounts

* *sumw*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>>
* *sumw2*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>> _(default: +None+)_
* *unweighted*: <<UnweightedCounts>> _(default: +None+)_=== InterpretedInlineBuffer

* *buffer*: buffer
* *filters*: list of Buffer.{Buffer.none, Buffer.gzip, Buffer.lzma, Buffer.lz4} _(default: +[]+)_
* *postfilter_slice*: slice (start:stop:step) _(default: +None+)_
* *dtype*: one of Interpretation.{Interpretation.none, Interpretation.bool, Interpretation.int8, Interpretation.uint8, Interpretation.int16, Interpretation.uint16, Interpretation.int32, Interpretation.uint32, Interpretation.int64, Interpretation.uint64, Interpretation.float32, Interpretation.float64} _(default: +Interpretation.none+)_
* *endianness*: one of Interpretation.{Interpretation.little_endian, Interpretation.big_endian} _(default: +Interpretation.little_endian+)_
* *dimension_order*: one of InterpretedBuffer.{InterpretedBuffer.c_order, InterpretedBuffer.fortran} _(default: +InterpretedBuffer.c_order+)_=== InterpretedInlineInt64Buffer

* *buffer*: buffer=== InterpretedInlineFloat64Buffer

* *buffer*: buffer=== InterpretedExternalBuffer

* *pointer*: int in _[0, inf)_
* *numbytes*: int in _[0, inf)_
* *external_source*: one of ExternalBuffer.{ExternalBuffer.memory, ExternalBuffer.samefile, ExternalBuffer.file, ExternalBuffer.url} _(default: +ExternalBuffer.memory+)_
* *filters*: list of Buffer.{Buffer.none, Buffer.gzip, Buffer.lzma, Buffer.lz4} _(default: +[]+)_
* *postfilter_slice*: slice (start:stop:step) _(default: +None+)_
* *dtype*: one of Interpretation.{Interpretation.none, Interpretation.bool, Interpretation.int8, Interpretation.uint8, Interpretation.int16, Interpretation.uint16, Interpretation.int32, Interpretation.uint32, Interpretation.int64, Interpretation.uint64, Interpretation.float32, Interpretation.float64} _(default: +Interpretation.none+)_
* *endianness*: one of Interpretation.{Interpretation.little_endian, Interpretation.big_endian} _(default: +Interpretation.little_endian+)_
* *dimension_order*: one of InterpretedBuffer.{InterpretedBuffer.c_order, InterpretedBuffer.fortran} _(default: +InterpretedBuffer.c_order+)_
* *location*: str _(default: +None+)_=== Profile

* *expression*: str
* *statistics*: <<Statistics>>
* *title*: str _(default: +None+)_
* *metadata*: <<Metadata>> _(default: +None+)_
* *decoration*: <<Decoration>> _(default: +None+)_=== Statistics

* *moments*: list of <<Moments>> _(default: +[]+)_
* *quantiles*: list of <<Quantiles>> _(default: +[]+)_
* *mode*: <<Modes>> _(default: +None+)_
* *min*: <<Extremes>> _(default: +None+)_
* *max*: <<Extremes>> _(default: +None+)_=== Moments

* *sumwxn*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>>
* *n*: int in _[-128, 127]_
* *weightpower*: int in _[-128, 127]_ _(default: +0+)_
* *filter*: <<StatisticFilter>> _(default: +None+)_=== Quantiles

* *values*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>>
* *p*: float in _[0.0, 1.0]_ _(default: +0.5+)_
* *weightpower*: int in _[-128, 127]_ _(default: +0+)_
* *filter*: <<StatisticFilter>> _(default: +None+)_=== Modes

* *values*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>>
* *filter*: <<StatisticFilter>> _(default: +None+)_=== Extremes

* *values*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>>
* *filter*: <<StatisticFilter>> _(default: +None+)_=== StatisticFilter

* *min*: float in _[-inf, inf]_ _(default: +-inf+)_
* *max*: float in _[-inf, inf]_ _(default: +inf+)_
* *excludes_minf*: bool _(default: +False+)_
* *excludes_pinf*: bool _(default: +False+)_
* *excludes_nan*: bool _(default: +False+)_=== Covariance

* *xindex*: int in _[0, inf)_
* *yindex*: int in _[0, inf)_
* *sumwxy*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>>
* *weightpower*: int in _[-128, 127]_ _(default: +0+)_
* *filter*: <<StatisticFilter>> _(default: +None+)_=== ParameterizedFunction

* *expression*: str
* *parameters*: list of <<Parameter>> _(default: +[]+)_
* *title*: str _(default: +None+)_
* *metadata*: <<Metadata>> _(default: +None+)_
* *decoration*: <<Decoration>> _(default: +None+)_
* *script*: str _(default: +None+)_=== Parameter

* *identifier*: unique str
* *values*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>>=== EvaluatedFunction

* *values*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>>
* *derivatives*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>> _(default: +None+)_
* *errors*: list of <<Quantiles>> _(default: +[]+)_
* *title*: str _(default: +None+)_
* *metadata*: <<Metadata>> _(default: +None+)_
* *decoration*: <<Decoration>> _(default: +None+)_
* *script*: str _(default: +None+)_=== BinnedEvaluatedFunction

* *axis*: list of <<Axis>> with length in _[1, inf)_
* *values*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>>
* *derivatives*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>> _(default: +None+)_
* *errors*: list of <<Quantiles>> _(default: +[]+)_
* *title*: str _(default: +None+)_
* *metadata*: <<Metadata>> _(default: +None+)_
* *decoration*: <<Decoration>> _(default: +None+)_
* *script*: str _(default: +None+)_=== Ntuple

* *columns*: list of <<Column>> with length in _[1, inf)_
* *instances*: list of <<NtupleInstance>> with length in _[1, inf)_
* *column_statistics*: list of <<Statistics>> _(default: +[]+)_
* *column_covariances*: list of <<Covariance>> _(default: +[]+)_
* *functions*: list of <<ParameterizedFunction>> or <<BinnedEvaluatedFunction>> _(default: +[]+)_
* *title*: str _(default: +None+)_
* *metadata*: <<Metadata>> _(default: +None+)_
* *decoration*: <<Decoration>> _(default: +None+)_
* *script*: str _(default: +None+)_=== Column

* *identifier*: unique str
* *dtype*: one of Interpretation.{Interpretation.none, Interpretation.bool, Interpretation.int8, Interpretation.uint8, Interpretation.int16, Interpretation.uint16, Interpretation.int32, Interpretation.uint32, Interpretation.int64, Interpretation.uint64, Interpretation.float32, Interpretation.float64}
* *endianness*: one of Interpretation.{Interpretation.little_endian, Interpretation.big_endian} _(default: +Interpretation.little_endian+)_
* *filters*: list of Buffer.{Buffer.none, Buffer.gzip, Buffer.lzma, Buffer.lz4} _(default: +[]+)_
* *postfilter_slice*: slice (start:stop:step) _(default: +None+)_
* *title*: str _(default: +None+)_
* *metadata*: <<Metadata>> _(default: +None+)_
* *decoration*: <<Decoration>> _(default: +None+)_=== NtupleInstance

* *chunks*: list of <<Chunk>>
* *chunk_offsets*: list of int _(default: +[]+)_=== Chunk

* *column_chunks*: list of <<ColumnChunk>>
* *metadata*: <<Metadata>> _(default: +None+)_=== ColumnChunk

* *pages*: list of <<Page>>
* *page_offsets*: list of int with length in _[1, inf)_
* *page_min*: list of <<Extremes>> _(default: +[]+)_
* *page_max*: list of <<Extremes>> _(default: +[]+)_=== Page

* *buffer*: <<RawInlineBuffer>> or <<RawExternalBuffer>>=== RawInlineBuffer

* *buffer*: buffer=== RawExternalBuffer

* *pointer*: int in _[0, inf)_
* *numbytes*: int in _[0, inf)_
* *external_source*: one of ExternalBuffer.{ExternalBuffer.memory, ExternalBuffer.samefile, ExternalBuffer.file, ExternalBuffer.url} _(default: +ExternalBuffer.memory+)_=== Metadata

* *data*: str
* *language*: one of Metadata.{Metadata.unspecified, Metadata.json} _(default: +Metadata.unspecified+)_=== Decoration

* *data*: str
* *language*: one of Decoration.{Decoration.unspecified, Decoration.css, Decoration.vega, Decoration.root_json} _(default: +Decoration.unspecified+)_
