


=== Collection

* *objects*: list of <<Histogram>> or <<Ntuple>> or <<ParameterizedFunction>> or <<BinnedEvaluatedFunction>> or <<Collection>> (default: +[]+)
* *axis*: list of <<Axis>> (default: +[]+)
* *title*: str (default: +None+)
* *metadata*: <<Metadata>> (default: +None+)
* *decoration*: <<Decoration>> (default: +None+)
* *script*: str (default: +None+)

=== Histogram

* *axis*: list of <<Axis>> with length in _[1, inf)_
* *counts*: <<UnweightedCounts>> or <<WeightedCounts>>
* *profile*: list of <<Profile>> (default: +[]+)
* *axis_covariances*: list of <<Covariance>> (default: +[]+)
* *profile_covariances*: list of <<Covariance>> (default: +[]+)
* *functions*: list of <<ParameterizedFunction>> or <<EvaluatedFunction>> (default: +[]+)
* *title*: str (default: +None+)
* *metadata*: <<Metadata>> (default: +None+)
* *decoration*: <<Decoration>> (default: +None+)
* *script*: str (default: +None+)

=== Axis

* *binning*: <<IntegerBinning>> or <<RegularBinning>> or <<HexagonalBinning>> or <<EdgesBinning>> or <<IrregularBinning>> or <<CategoryBinning>> or <<SparseRegularBinning>> or <<FractionBinning>> or <<PredicateBinning>> or <<VariationBinning>> (default: +None+)
* *expression*: str (default: +None+)
* *statistics*: <<Statistics>> (default: +None+)
* *title*: str (default: +None+)
* *metadata*: <<Metadata>> (default: +None+)
* *decoration*: <<Decoration>> (default: +None+)

=== IntegerBinning

* *min*: int in _(-inf, inf)_
* *max*: int in _(-inf, inf)_
* *loc_underflow*: one of BinLocation.{BinLocation.below3, BinLocation.below2, BinLocation.below1, BinLocation.nonexistent, BinLocation.above1, BinLocation.above2, BinLocation.above3} (default: +BinLocation.nonexistent+)
* *loc_overflow*: one of BinLocation.{BinLocation.below3, BinLocation.below2, BinLocation.below1, BinLocation.nonexistent, BinLocation.above1, BinLocation.above2, BinLocation.above3} (default: +BinLocation.nonexistent+)

=== RegularBinning

* *num*: int in _[1, inf)_
* *interval*: <<RealInterval>>
* *overflow*: <<RealOverflow>> (default: +None+)
* *circular*: bool (default: +False+)

=== RealInterval

* *low*: float in _[-inf, inf]_
* *high*: float in _[-inf, inf]_
* *low_inclusive*: bool (default: +True+)
* *high_inclusive*: bool (default: +False+)

=== RealOverflow

* *loc_underflow*: one of BinLocation.{BinLocation.below3, BinLocation.below2, BinLocation.below1, BinLocation.nonexistent, BinLocation.above1, BinLocation.above2, BinLocation.above3} (default: +BinLocation.nonexistent+)
* *loc_overflow*: one of BinLocation.{BinLocation.below3, BinLocation.below2, BinLocation.below1, BinLocation.nonexistent, BinLocation.above1, BinLocation.above2, BinLocation.above3} (default: +BinLocation.nonexistent+)
* *loc_nanflow*: one of BinLocation.{BinLocation.below3, BinLocation.below2, BinLocation.below1, BinLocation.nonexistent, BinLocation.above1, BinLocation.above2, BinLocation.above3} (default: +BinLocation.nonexistent+)
* *minf_mapping*: one of RealOverflow.{RealOverflow.missing, RealOverflow.in_underflow, RealOverflow.in_overflow, RealOverflow.in_nanflow} (default: +RealOverflow.in_underflow+)
* *pinf_mapping*: one of RealOverflow.{RealOverflow.missing, RealOverflow.in_underflow, RealOverflow.in_overflow, RealOverflow.in_nanflow} (default: +RealOverflow.in_overflow+)
* *nan_mapping*: one of RealOverflow.{RealOverflow.missing, RealOverflow.in_underflow, RealOverflow.in_overflow, RealOverflow.in_nanflow} (default: +RealOverflow.in_nanflow+)

=== HexagonalBinning

* *qmin*: int in _(-inf, inf)_
* *qmax*: int in _(-inf, inf)_
* *rmin*: int in _(-inf, inf)_
* *rmax*: int in _(-inf, inf)_
* *coordinates*: one of HexagonalBinning.{HexagonalBinning.offset, HexagonalBinning.doubled_offset, HexagonalBinning.cube_xy, HexagonalBinning.cube_yz, HexagonalBinning.cube_xz} (default: +HexagonalBinning.offset+)
* *xorigin*: float in _(-inf, inf)_ (default: +0.0+)
* *yorigin*: float in _(-inf, inf)_ (default: +0.0+)
* *qangle*: float in _[-1.5707963267948966, 1.5707963267948966]_ (default: +0.0+)
* *qoverflow*: <<RealOverflow>> (default: +None+)
* *roverflow*: <<RealOverflow>> (default: +None+)

=== EdgesBinning

* *edges*: list of float with length in _[1, inf)_
* *overflow*: <<RealOverflow>> (default: +None+)
* *low_inclusive*: bool (default: +True+)
* *high_inclusive*: bool (default: +False+)
* *circular*: bool (default: +False+)

=== IrregularBinning

* *intervals*: list of <<RealInterval>> with length in _[1, inf)_
* *overflow*: <<RealOverflow>> (default: +None+)
* *overlapping_fill*: one of IrregularBinning.{IrregularBinning.undefined, IrregularBinning.all, IrregularBinning.first, IrregularBinning.last} (default: +IrregularBinning.undefined+)

=== CategoryBinning

* *categories*: list of str
* *loc_overflow*: one of BinLocation.{BinLocation.below3, BinLocation.below2, BinLocation.below1, BinLocation.nonexistent, BinLocation.above1, BinLocation.above2, BinLocation.above3} (default: +BinLocation.nonexistent+)

=== SparseRegularBinning

* *bins*: list of int
* *bin_width*: float in _(0, inf]_
* *origin*: float in _[-inf, inf]_ (default: +0.0+)
* *overflow*: <<RealOverflow>> (default: +None+)
* *low_inclusive*: bool (default: +True+)
* *high_inclusive*: bool (default: +False+)
* *minbin*: int in _[-9223372036854775808, 9223372036854775807]_ (default: +-9223372036854775808+)
* *maxbin*: int in _[-9223372036854775808, 9223372036854775807]_ (default: +9223372036854775807+)

=== FractionBinning

* *layout*: one of FractionBinning.{FractionBinning.passall, FractionBinning.failall, FractionBinning.passfail} (default: +FractionBinning.passall+)
* *layout_reversed*: bool (default: +False+)
* *error_method*: one of FractionBinning.{FractionBinning.undefined, FractionBinning.normal, FractionBinning.clopper_pearson, FractionBinning.wilson, FractionBinning.agresti_coull, FractionBinning.feldman_cousins, FractionBinning.jeffrey, FractionBinning.bayesian_uniform} (default: +FractionBinning.undefined+)

=== PredicateBinning

* *predicates*: list of str with length in _[1, inf)_
* *overlapping_fill*: one of IrregularBinning.{IrregularBinning.undefined, IrregularBinning.all, IrregularBinning.first, IrregularBinning.last} (default: +IrregularBinning.undefined+)

=== VariationBinning

* *variations*: list of <<Variation>> with length in _[1, inf)_

=== Variation

* *assignments*: list of <<Assignment>>
* *systematic*: list of float (default: +[]+)
* *category_systematic*: list of str (default: +[]+)

=== Assignment

* *identifier*: unique str
* *expression*: str

=== UnweightedCounts

* *counts*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>>

=== WeightedCounts

* *sumw*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>>
* *sumw2*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>> (default: +None+)
* *unweighted*: <<UnweightedCounts>> (default: +None+)

=== InterpretedInlineBuffer

* *buffer*: buffer
* *filters*: list of Buffer.{Buffer.none, Buffer.gzip, Buffer.lzma, Buffer.lz4} (default: +[]+)
* *postfilter_slice*: slice (start:stop:step) (default: +None+)
* *dtype*: one of Interpretation.{Interpretation.none, Interpretation.bool, Interpretation.int8, Interpretation.uint8, Interpretation.int16, Interpretation.uint16, Interpretation.int32, Interpretation.uint32, Interpretation.int64, Interpretation.uint64, Interpretation.float32, Interpretation.float64} (default: +Interpretation.none+)
* *endianness*: one of Interpretation.{Interpretation.little_endian, Interpretation.big_endian} (default: +Interpretation.little_endian+)
* *dimension_order*: one of InterpretedBuffer.{InterpretedBuffer.c_order, InterpretedBuffer.fortran} (default: +InterpretedBuffer.c_order+)

=== InterpretedInlineInt64Buffer

* *buffer*: buffer

=== InterpretedInlineFloat64Buffer

* *buffer*: buffer

=== InterpretedExternalBuffer

* *pointer*: int in _[0, inf)_
* *numbytes*: int in _[0, inf)_
* *external_source*: one of ExternalBuffer.{ExternalBuffer.memory, ExternalBuffer.samefile, ExternalBuffer.file, ExternalBuffer.url} (default: +ExternalBuffer.memory+)
* *filters*: list of Buffer.{Buffer.none, Buffer.gzip, Buffer.lzma, Buffer.lz4} (default: +[]+)
* *postfilter_slice*: slice (start:stop:step) (default: +None+)
* *dtype*: one of Interpretation.{Interpretation.none, Interpretation.bool, Interpretation.int8, Interpretation.uint8, Interpretation.int16, Interpretation.uint16, Interpretation.int32, Interpretation.uint32, Interpretation.int64, Interpretation.uint64, Interpretation.float32, Interpretation.float64} (default: +Interpretation.none+)
* *endianness*: one of Interpretation.{Interpretation.little_endian, Interpretation.big_endian} (default: +Interpretation.little_endian+)
* *dimension_order*: one of InterpretedBuffer.{InterpretedBuffer.c_order, InterpretedBuffer.fortran} (default: +InterpretedBuffer.c_order+)
* *location*: str (default: +None+)

=== Profile

* *expression*: str
* *statistics*: <<Statistics>>
* *title*: str (default: +None+)
* *metadata*: <<Metadata>> (default: +None+)
* *decoration*: <<Decoration>> (default: +None+)

=== Statistics

* *moments*: list of <<Moments>> (default: +[]+)
* *quantiles*: list of <<Quantiles>> (default: +[]+)
* *mode*: <<Modes>> (default: +None+)
* *min*: <<Extremes>> (default: +None+)
* *max*: <<Extremes>> (default: +None+)

=== Moments

* *sumwxn*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>>
* *n*: int in _[-128, 127]_
* *weightpower*: int in _[-128, 127]_ (default: +0+)
* *filter*: <<StatisticFilter>> (default: +None+)

=== Quantiles

* *values*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>>
* *p*: float in _[0.0, 1.0]_ (default: +0.5+)
* *weightpower*: int in _[-128, 127]_ (default: +0+)
* *filter*: <<StatisticFilter>> (default: +None+)

=== Modes

* *values*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>>
* *filter*: <<StatisticFilter>> (default: +None+)

=== Extremes

* *values*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>>
* *filter*: <<StatisticFilter>> (default: +None+)

=== StatisticFilter

* *min*: float in _[-inf, inf]_ (default: +-inf+)
* *max*: float in _[-inf, inf]_ (default: +inf+)
* *excludes_minf*: bool (default: +False+)
* *excludes_pinf*: bool (default: +False+)
* *excludes_nan*: bool (default: +False+)

=== Covariance

* *xindex*: int in _[0, inf)_
* *yindex*: int in _[0, inf)_
* *sumwxy*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>>
* *weightpower*: int in _[-128, 127]_ (default: +0+)
* *filter*: <<StatisticFilter>> (default: +None+)

=== ParameterizedFunction

* *expression*: str
* *parameters*: list of <<Parameter>> (default: +[]+)
* *title*: str (default: +None+)
* *metadata*: <<Metadata>> (default: +None+)
* *decoration*: <<Decoration>> (default: +None+)
* *script*: str (default: +None+)

=== Parameter

* *identifier*: unique str
* *values*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>>

=== EvaluatedFunction

* *values*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>>
* *derivatives*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>> (default: +None+)
* *errors*: list of <<Quantiles>> (default: +[]+)
* *title*: str (default: +None+)
* *metadata*: <<Metadata>> (default: +None+)
* *decoration*: <<Decoration>> (default: +None+)
* *script*: str (default: +None+)

=== BinnedEvaluatedFunction

* *axis*: list of <<Axis>> with length in _[1, inf)_
* *values*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>>
* *derivatives*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>> (default: +None+)
* *errors*: list of <<Quantiles>> (default: +[]+)
* *title*: str (default: +None+)
* *metadata*: <<Metadata>> (default: +None+)
* *decoration*: <<Decoration>> (default: +None+)
* *script*: str (default: +None+)

=== Ntuple

* *columns*: list of <<Column>> with length in _[1, inf)_
* *instances*: list of <<NtupleInstance>> with length in _[1, inf)_
* *column_statistics*: list of <<Statistics>> (default: +[]+)
* *column_covariances*: list of <<Covariance>> (default: +[]+)
* *functions*: list of <<ParameterizedFunction>> or <<BinnedEvaluatedFunction>> (default: +[]+)
* *title*: str (default: +None+)
* *metadata*: <<Metadata>> (default: +None+)
* *decoration*: <<Decoration>> (default: +None+)
* *script*: str (default: +None+)

=== Column

* *identifier*: unique str
* *dtype*: one of Interpretation.{Interpretation.none, Interpretation.bool, Interpretation.int8, Interpretation.uint8, Interpretation.int16, Interpretation.uint16, Interpretation.int32, Interpretation.uint32, Interpretation.int64, Interpretation.uint64, Interpretation.float32, Interpretation.float64}
* *endianness*: one of Interpretation.{Interpretation.little_endian, Interpretation.big_endian} (default: +Interpretation.little_endian+)
* *filters*: list of Buffer.{Buffer.none, Buffer.gzip, Buffer.lzma, Buffer.lz4} (default: +[]+)
* *postfilter_slice*: slice (start:stop:step) (default: +None+)
* *title*: str (default: +None+)
* *metadata*: <<Metadata>> (default: +None+)
* *decoration*: <<Decoration>> (default: +None+)

=== NtupleInstance

* *chunks*: list of <<Chunk>>
* *chunk_offsets*: list of int (default: +[]+)

=== Chunk

* *column_chunks*: list of <<ColumnChunk>>
* *metadata*: <<Metadata>> (default: +None+)

=== ColumnChunk

* *pages*: list of <<Page>>
* *page_offsets*: list of int with length in _[1, inf)_
* *page_min*: list of <<Extremes>> (default: +[]+)
* *page_max*: list of <<Extremes>> (default: +[]+)

=== Page

* *buffer*: <<RawInlineBuffer>> or <<RawExternalBuffer>>

=== RawInlineBuffer

* *buffer*: buffer

=== RawExternalBuffer

* *pointer*: int in _[0, inf)_
* *numbytes*: int in _[0, inf)_
* *external_source*: one of ExternalBuffer.{ExternalBuffer.memory, ExternalBuffer.samefile, ExternalBuffer.file, ExternalBuffer.url} (default: +ExternalBuffer.memory+)

=== Metadata

* *data*: str
* *language*: one of Metadata.{Metadata.unspecified, Metadata.json} (default: +Metadata.unspecified+)

=== Decoration

* *data*: str
* *language*: one of Decoration.{Decoration.unspecified, Decoration.css, Decoration.vega, Decoration.root_json} (default: +Decoration.unspecified+)
