= Stagg Specification

== Introduction

== Types

== Class definitions



=== Collection

[%hardbreaks]
•{nbsp} *objects*: str → <<Histogram>> or <<Ntuple>> or <<ParameterizedFunction>> or <<BinnedEvaluatedFunction>> or <<Collection>> +
(default: null/empty)
•{nbsp} *axis*: list of <<Axis>> (default: null/empty)
•{nbsp} *title*: str (default: null)
•{nbsp} *metadata*: <<Metadata>> (default: null)
•{nbsp} *decoration*: <<Decoration>> (default: null)
•{nbsp} *script*: str (default: null)

{empty} +
Collection of named objects, possibly with one or more common axis.

{empty} +
Can be used to gather objects into a convenient package or to avoid duplication when defining similarly binned data. As an example of the latter, consider histograms three `h1`, `h2`, `h3` with two sets of cuts applied, `signal` and `control` (six histograms total).

    Collection({"h1": h1, "h2": h2, "h3": h3},
               axis=[Axis(PredicateBinning("signal"), PredicateBinning("control"))])

This signal/control axis (defined by a predicate when filling: if in signal region, if in control region) is prepended onto each histogram's own axis. For instance, if `h1` had one regular axis and `h2` had two irregular axes, the `"h1"` in this Collection has two axes: predicate, then regular, and the `"h2"` in this Collection has three axes: predicate, then irregular, then irregular.

To subdivide one set of objects and not another, or to subdivide two sets of objects differently, put Collections inside of collections. In the following example, `h1` is not subdivided but `h2` and `h3` are.

    Collection({"h1": h1,
                "cut by region":
                    Collection({"h2": h2, "h3": h3},
                    axis=[Axis(PredicateBinning("signal"), PredicateBinning("control"))])})

Similarly, regions can be subdivided into subregions, and other binning types may be used.

=== Histogram

[%hardbreaks]
•{nbsp}required  *axis*: list of <<Axis>> with length in [1, ∞)
•{nbsp}required  *counts*: <<UnweightedCounts>> or <<WeightedCounts>>
•{nbsp} *profile*: list of <<Profile>> (default: null/empty)
•{nbsp} *axis_covariances*: list of <<Covariance>> (default: null/empty)
•{nbsp} *profile_covariances*: list of <<Covariance>> (default: null/empty)
•{nbsp} *functions*: str → <<ParameterizedFunction>> or <<EvaluatedFunction>> (default: null/empty)
•{nbsp} *title*: str (default: null)
•{nbsp} *metadata*: <<Metadata>> (default: null)
•{nbsp} *decoration*: <<Decoration>> (default: null)
•{nbsp} *script*: str (default: null)

{empty} +


{empty} +


=== Axis

[%hardbreaks]
•{nbsp} *binning*: <<IntegerBinning>> or <<RegularBinning>> or <<HexagonalBinning>> or <<EdgesBinning>> or <<IrregularBinning>> or <<CategoryBinning>> or <<SparseRegularBinning>> or <<FractionBinning>> or <<PredicateBinning>> or <<VariationBinning>> +
(default: null)
•{nbsp} *expression*: str (default: null)
•{nbsp} *statistics*: <<Statistics>> (default: null)
•{nbsp} *title*: str (default: null)
•{nbsp} *metadata*: <<Metadata>> (default: null)
•{nbsp} *decoration*: <<Decoration>> (default: null)

{empty} +


{empty} +


=== IntegerBinning

[%hardbreaks]
•{nbsp}required  *min*: int in (‒∞, ∞)
•{nbsp}required  *max*: int in (‒∞, ∞)
•{nbsp} *loc_underflow*: one of {`+BinLocation.below3+`, `+BinLocation.below2+`, `+BinLocation.below1+`, `+BinLocation.nonexistent+`, `+BinLocation.above1+`, `+BinLocation.above2+`, `+BinLocation.above3+`} +
(default: `+BinLocation.nonexistent+`)
•{nbsp} *loc_overflow*: one of {`+BinLocation.below3+`, `+BinLocation.below2+`, `+BinLocation.below1+`, `+BinLocation.nonexistent+`, `+BinLocation.above1+`, `+BinLocation.above2+`, `+BinLocation.above3+`} +
(default: `+BinLocation.nonexistent+`)

{empty} +


{empty} +


=== RegularBinning

[%hardbreaks]
•{nbsp}required  *num*: int in [1, ∞)
•{nbsp}required  *interval*: <<RealInterval>>
•{nbsp} *overflow*: <<RealOverflow>> (default: null)
•{nbsp} *circular*: bool (default: false)

{empty} +


{empty} +


=== RealInterval

[%hardbreaks]
•{nbsp}required  *low*: float in [‒∞, ∞]
•{nbsp}required  *high*: float in [‒∞, ∞]
•{nbsp} *low_inclusive*: bool (default: true)
•{nbsp} *high_inclusive*: bool (default: false)

{empty} +


{empty} +


=== RealOverflow

[%hardbreaks]
•{nbsp} *loc_underflow*: one of {`+BinLocation.below3+`, `+BinLocation.below2+`, `+BinLocation.below1+`, `+BinLocation.nonexistent+`, `+BinLocation.above1+`, `+BinLocation.above2+`, `+BinLocation.above3+`} +
(default: `+BinLocation.nonexistent+`)
•{nbsp} *loc_overflow*: one of {`+BinLocation.below3+`, `+BinLocation.below2+`, `+BinLocation.below1+`, `+BinLocation.nonexistent+`, `+BinLocation.above1+`, `+BinLocation.above2+`, `+BinLocation.above3+`} +
(default: `+BinLocation.nonexistent+`)
•{nbsp} *loc_nanflow*: one of {`+BinLocation.below3+`, `+BinLocation.below2+`, `+BinLocation.below1+`, `+BinLocation.nonexistent+`, `+BinLocation.above1+`, `+BinLocation.above2+`, `+BinLocation.above3+`} +
(default: `+BinLocation.nonexistent+`)
•{nbsp} *minf_mapping*: one of {`+RealOverflow.missing+`, `+RealOverflow.in_underflow+`, `+RealOverflow.in_overflow+`, `+RealOverflow.in_nanflow+`} +
(default: `+RealOverflow.in_underflow+`)
•{nbsp} *pinf_mapping*: one of {`+RealOverflow.missing+`, `+RealOverflow.in_underflow+`, `+RealOverflow.in_overflow+`, `+RealOverflow.in_nanflow+`} +
(default: `+RealOverflow.in_overflow+`)
•{nbsp} *nan_mapping*: one of {`+RealOverflow.missing+`, `+RealOverflow.in_underflow+`, `+RealOverflow.in_overflow+`, `+RealOverflow.in_nanflow+`} +
(default: `+RealOverflow.in_nanflow+`)

{empty} +


{empty} +


=== HexagonalBinning

[%hardbreaks]
•{nbsp}required  *qmin*: int in (‒∞, ∞)
•{nbsp}required  *qmax*: int in (‒∞, ∞)
•{nbsp}required  *rmin*: int in (‒∞, ∞)
•{nbsp}required  *rmax*: int in (‒∞, ∞)
•{nbsp} *coordinates*: one of {`+HexagonalBinning.offset+`, `+HexagonalBinning.doubled_offset+`, `+HexagonalBinning.cube_xy+`, `+HexagonalBinning.cube_yz+`, `+HexagonalBinning.cube_xz+`} +
(default: `+HexagonalBinning.offset+`)
•{nbsp} *xorigin*: float in (‒∞, ∞) (default: 0.0)
•{nbsp} *yorigin*: float in (‒∞, ∞) (default: 0.0)
•{nbsp} *qangle*: float in [‒π/2, π/2] (default: 0.0)
•{nbsp} *qoverflow*: <<RealOverflow>> (default: null)
•{nbsp} *roverflow*: <<RealOverflow>> (default: null)

{empty} +


{empty} +


=== EdgesBinning

[%hardbreaks]
•{nbsp}required  *edges*: list of float with length in [1, ∞)
•{nbsp} *overflow*: <<RealOverflow>> (default: null)
•{nbsp} *low_inclusive*: bool (default: true)
•{nbsp} *high_inclusive*: bool (default: false)
•{nbsp} *circular*: bool (default: false)

{empty} +


{empty} +


=== IrregularBinning

[%hardbreaks]
•{nbsp}required  *intervals*: list of <<RealInterval>> with length in [1, ∞)
•{nbsp} *overflow*: <<RealOverflow>> (default: null)
•{nbsp} *overlapping_fill*: one of {`+IrregularBinning.undefined+`, `+IrregularBinning.all+`, `+IrregularBinning.first+`, `+IrregularBinning.last+`} +
(default: `+IrregularBinning.undefined+`)

{empty} +


{empty} +


=== CategoryBinning

[%hardbreaks]
•{nbsp}required  *categories*: list of str
•{nbsp} *loc_overflow*: one of {`+BinLocation.below3+`, `+BinLocation.below2+`, `+BinLocation.below1+`, `+BinLocation.nonexistent+`, `+BinLocation.above1+`, `+BinLocation.above2+`, `+BinLocation.above3+`} +
(default: `+BinLocation.nonexistent+`)

{empty} +


{empty} +


=== SparseRegularBinning

[%hardbreaks]
•{nbsp}required  *bins*: list of int
•{nbsp}required  *bin_width*: float in (0, ∞]
•{nbsp} *origin*: float in [‒∞, ∞] (default: 0.0)
•{nbsp} *overflow*: <<RealOverflow>> (default: null)
•{nbsp} *low_inclusive*: bool (default: true)
•{nbsp} *high_inclusive*: bool (default: false)
•{nbsp} *minbin*: int in [‒2⁶³, 2⁶³ ‒ 1] (default: ‒2⁶³)
•{nbsp} *maxbin*: int in [‒2⁶³, 2⁶³ ‒ 1] (default: 2⁶³ ‒ 1)

{empty} +


{empty} +


=== FractionBinning

[%hardbreaks]
•{nbsp} *layout*: one of {`+FractionBinning.passall+`, `+FractionBinning.failall+`, `+FractionBinning.passfail+`} +
(default: `+FractionBinning.passall+`)
•{nbsp} *layout_reversed*: bool (default: false)
•{nbsp} *error_method*: one of {`+FractionBinning.undefined+`, `+FractionBinning.normal+`, `+FractionBinning.clopper_pearson+`, `+FractionBinning.wilson+`, `+FractionBinning.agresti_coull+`, `+FractionBinning.feldman_cousins+`, `+FractionBinning.jeffrey+`, `+FractionBinning.bayesian_uniform+`} +
(default: `+FractionBinning.undefined+`)

{empty} +


{empty} +


=== PredicateBinning

[%hardbreaks]
•{nbsp}required  *predicates*: list of str with length in [1, ∞)
•{nbsp} *overlapping_fill*: one of {`+IrregularBinning.undefined+`, `+IrregularBinning.all+`, `+IrregularBinning.first+`, `+IrregularBinning.last+`} +
(default: `+IrregularBinning.undefined+`)

{empty} +


{empty} +


=== VariationBinning

[%hardbreaks]
•{nbsp}required  *variations*: list of <<Variation>> with length in [1, ∞)

{empty} +


{empty} +


=== Variation

[%hardbreaks]
•{nbsp}required  *assignments*: list of <<Assignment>>
•{nbsp} *systematic*: list of float (default: null/empty)
•{nbsp} *category_systematic*: list of str (default: null/empty)

{empty} +


{empty} +


=== Assignment

[%hardbreaks]
•{nbsp}required  *identifier*: unique str
•{nbsp}required  *expression*: str

{empty} +


{empty} +


=== UnweightedCounts

[%hardbreaks]
•{nbsp}required  *counts*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>>

{empty} +


{empty} +


=== WeightedCounts

[%hardbreaks]
•{nbsp}required  *sumw*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>>
•{nbsp} *sumw2*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>> +
(default: null)
•{nbsp} *unweighted*: <<UnweightedCounts>> (default: null)

{empty} +


{empty} +


=== InterpretedInlineBuffer

[%hardbreaks]
•{nbsp}required  *buffer*: buffer
•{nbsp} *filters*: list of {`+Buffer.none+`, `+Buffer.gzip+`, `+Buffer.lzma+`, `+Buffer.lz4+`} +
(default: null/empty)
•{nbsp} *postfilter_slice*: slice (start:stop:step) (default: null)
•{nbsp} *dtype*: one of {`+Interpretation.none+`, `+Interpretation.bool+`, `+Interpretation.int8+`, `+Interpretation.uint8+`, `+Interpretation.int16+`, `+Interpretation.uint16+`, `+Interpretation.int32+`, `+Interpretation.uint32+`, `+Interpretation.int64+`, `+Interpretation.uint64+`, `+Interpretation.float32+`, `+Interpretation.float64+`} +
(default: `+Interpretation.none+`)
•{nbsp} *endianness*: one of {`+Interpretation.little_endian+`, `+Interpretation.big_endian+`} +
(default: `+Interpretation.little_endian+`)
•{nbsp} *dimension_order*: one of {`+InterpretedBuffer.c_order+`, `+InterpretedBuffer.fortran+`} +
(default: `+InterpretedBuffer.c_order+`)

{empty} +


{empty} +


=== InterpretedInlineInt64Buffer

[%hardbreaks]
•{nbsp}required  *buffer*: buffer

{empty} +


{empty} +


=== InterpretedInlineFloat64Buffer

[%hardbreaks]
•{nbsp}required  *buffer*: buffer

{empty} +


{empty} +


=== InterpretedExternalBuffer

[%hardbreaks]
•{nbsp}required  *pointer*: int in [0, ∞)
•{nbsp}required  *numbytes*: int in [0, ∞)
•{nbsp} *external_source*: one of {`+ExternalBuffer.memory+`, `+ExternalBuffer.samefile+`, `+ExternalBuffer.file+`, `+ExternalBuffer.url+`} +
(default: `+ExternalBuffer.memory+`)
•{nbsp} *filters*: list of {`+Buffer.none+`, `+Buffer.gzip+`, `+Buffer.lzma+`, `+Buffer.lz4+`} +
(default: null/empty)
•{nbsp} *postfilter_slice*: slice (start:stop:step) (default: null)
•{nbsp} *dtype*: one of {`+Interpretation.none+`, `+Interpretation.bool+`, `+Interpretation.int8+`, `+Interpretation.uint8+`, `+Interpretation.int16+`, `+Interpretation.uint16+`, `+Interpretation.int32+`, `+Interpretation.uint32+`, `+Interpretation.int64+`, `+Interpretation.uint64+`, `+Interpretation.float32+`, `+Interpretation.float64+`} +
(default: `+Interpretation.none+`)
•{nbsp} *endianness*: one of {`+Interpretation.little_endian+`, `+Interpretation.big_endian+`} +
(default: `+Interpretation.little_endian+`)
•{nbsp} *dimension_order*: one of {`+InterpretedBuffer.c_order+`, `+InterpretedBuffer.fortran+`} +
(default: `+InterpretedBuffer.c_order+`)
•{nbsp} *location*: str (default: null)

{empty} +


{empty} +


=== Profile

[%hardbreaks]
•{nbsp}required  *expression*: str
•{nbsp}required  *statistics*: <<Statistics>>
•{nbsp} *title*: str (default: null)
•{nbsp} *metadata*: <<Metadata>> (default: null)
•{nbsp} *decoration*: <<Decoration>> (default: null)

{empty} +


{empty} +


=== Statistics

[%hardbreaks]
•{nbsp} *moments*: list of <<Moments>> (default: null/empty)
•{nbsp} *quantiles*: list of <<Quantiles>> (default: null/empty)
•{nbsp} *mode*: <<Modes>> (default: null)
•{nbsp} *min*: <<Extremes>> (default: null)
•{nbsp} *max*: <<Extremes>> (default: null)

{empty} +


{empty} +


=== Moments

[%hardbreaks]
•{nbsp}required  *sumwxn*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>>
•{nbsp}required  *n*: int in [‒128, 127]
•{nbsp} *weightpower*: int in [‒128, 127] (default: 0)
•{nbsp} *filter*: <<StatisticFilter>> (default: null)

{empty} +


{empty} +


=== Quantiles

[%hardbreaks]
•{nbsp}required  *values*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>>
•{nbsp}required  *p*: float in [0.0, 1.0] (default: 1/2)
•{nbsp} *weightpower*: int in [‒128, 127] (default: 0)
•{nbsp} *filter*: <<StatisticFilter>> (default: null)

{empty} +


{empty} +


=== Modes

[%hardbreaks]
•{nbsp}required  *values*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>>
•{nbsp} *filter*: <<StatisticFilter>> (default: null)

{empty} +


{empty} +


=== Extremes

[%hardbreaks]
•{nbsp}required  *values*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>>
•{nbsp} *filter*: <<StatisticFilter>> (default: null)

{empty} +


{empty} +


=== StatisticFilter

[%hardbreaks]
•{nbsp} *min*: float in [‒∞, ∞] (default: ‒∞)
•{nbsp} *max*: float in [‒∞, ∞] (default: ∞)
•{nbsp} *excludes_minf*: bool (default: false)
•{nbsp} *excludes_pinf*: bool (default: false)
•{nbsp} *excludes_nan*: bool (default: false)

{empty} +


{empty} +


=== Covariance

[%hardbreaks]
•{nbsp}required  *xindex*: int in [0, ∞)
•{nbsp}required  *yindex*: int in [0, ∞)
•{nbsp}required  *sumwxy*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>>
•{nbsp} *weightpower*: int in [‒128, 127] (default: 0)
•{nbsp} *filter*: <<StatisticFilter>> (default: null)

{empty} +


{empty} +


=== ParameterizedFunction

[%hardbreaks]
•{nbsp}required  *expression*: str
•{nbsp} *parameters*: list of <<Parameter>> (default: null/empty)
•{nbsp} *title*: str (default: null)
•{nbsp} *metadata*: <<Metadata>> (default: null)
•{nbsp} *decoration*: <<Decoration>> (default: null)
•{nbsp} *script*: str (default: null)

{empty} +


{empty} +


=== Parameter

[%hardbreaks]
•{nbsp}required  *identifier*: unique str
•{nbsp}required  *values*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>>

{empty} +


{empty} +


=== EvaluatedFunction

[%hardbreaks]
•{nbsp}required  *values*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>>
•{nbsp} *derivatives*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>> +
(default: null)
•{nbsp} *errors*: list of <<Quantiles>> (default: null/empty)
•{nbsp} *title*: str (default: null)
•{nbsp} *metadata*: <<Metadata>> (default: null)
•{nbsp} *decoration*: <<Decoration>> (default: null)
•{nbsp} *script*: str (default: null)

{empty} +


{empty} +


=== BinnedEvaluatedFunction

[%hardbreaks]
•{nbsp}required  *axis*: list of <<Axis>> with length in [1, ∞)
•{nbsp}required  *values*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>>
•{nbsp} *derivatives*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>> +
(default: null)
•{nbsp} *errors*: list of <<Quantiles>> (default: null/empty)
•{nbsp} *title*: str (default: null)
•{nbsp} *metadata*: <<Metadata>> (default: null)
•{nbsp} *decoration*: <<Decoration>> (default: null)
•{nbsp} *script*: str (default: null)

{empty} +


{empty} +


=== Ntuple

[%hardbreaks]
•{nbsp}required  *columns*: list of <<Column>> with length in [1, ∞)
•{nbsp}required  *instances*: list of <<NtupleInstance>> with length in [1, ∞)
•{nbsp} *column_statistics*: list of <<Statistics>> (default: null/empty)
•{nbsp} *column_covariances*: list of <<Covariance>> (default: null/empty)
•{nbsp} *functions*: str → <<ParameterizedFunction>> or <<BinnedEvaluatedFunction>> (default: null/empty)
•{nbsp} *title*: str (default: null)
•{nbsp} *metadata*: <<Metadata>> (default: null)
•{nbsp} *decoration*: <<Decoration>> (default: null)
•{nbsp} *script*: str (default: null)

{empty} +


{empty} +


=== Column

[%hardbreaks]
•{nbsp}required  *identifier*: unique str
•{nbsp}required  *dtype*: one of {`+Interpretation.none+`, `+Interpretation.bool+`, `+Interpretation.int8+`, `+Interpretation.uint8+`, `+Interpretation.int16+`, `+Interpretation.uint16+`, `+Interpretation.int32+`, `+Interpretation.uint32+`, `+Interpretation.int64+`, `+Interpretation.uint64+`, `+Interpretation.float32+`, `+Interpretation.float64+`}
•{nbsp} *endianness*: one of {`+Interpretation.little_endian+`, `+Interpretation.big_endian+`} +
(default: `+Interpretation.little_endian+`)
•{nbsp} *filters*: list of {`+Buffer.none+`, `+Buffer.gzip+`, `+Buffer.lzma+`, `+Buffer.lz4+`} +
(default: null/empty)
•{nbsp} *postfilter_slice*: slice (start:stop:step) (default: null)
•{nbsp} *title*: str (default: null)
•{nbsp} *metadata*: <<Metadata>> (default: null)
•{nbsp} *decoration*: <<Decoration>> (default: null)

{empty} +


{empty} +


=== NtupleInstance

[%hardbreaks]
•{nbsp}required  *chunks*: list of <<Chunk>>
•{nbsp} *chunk_offsets*: list of int (default: null/empty)

{empty} +


{empty} +


=== Chunk

[%hardbreaks]
•{nbsp}required  *column_chunks*: list of <<ColumnChunk>>
•{nbsp} *metadata*: <<Metadata>> (default: null)

{empty} +


{empty} +


=== ColumnChunk

[%hardbreaks]
•{nbsp}required  *pages*: list of <<Page>>
•{nbsp}required  *page_offsets*: list of int with length in [1, ∞)
•{nbsp} *page_min*: list of <<Extremes>> (default: null/empty)
•{nbsp} *page_max*: list of <<Extremes>> (default: null/empty)

{empty} +


{empty} +


=== Page

[%hardbreaks]
•{nbsp}required  *buffer*: <<RawInlineBuffer>> or <<RawExternalBuffer>>

{empty} +


{empty} +


=== RawInlineBuffer

[%hardbreaks]
•{nbsp}required  *buffer*: buffer

{empty} +


{empty} +


=== RawExternalBuffer

[%hardbreaks]
•{nbsp}required  *pointer*: int in [0, ∞)
•{nbsp}required  *numbytes*: int in [0, ∞)
•{nbsp} *external_source*: one of {`+ExternalBuffer.memory+`, `+ExternalBuffer.samefile+`, `+ExternalBuffer.file+`, `+ExternalBuffer.url+`} +
(default: `+ExternalBuffer.memory+`)

{empty} +


{empty} +


=== Metadata

[%hardbreaks]
•{nbsp}required  *data*: str
•{nbsp}required  *language*: one of {`+Metadata.unspecified+`, `+Metadata.json+`} (default: `+Metadata.unspecified+`)

{empty} +


{empty} +


=== Decoration

[%hardbreaks]
•{nbsp}required  *data*: str
•{nbsp}required  *language*: one of {`+Decoration.unspecified+`, `+Decoration.css+`, `+Decoration.vega+`, `+Decoration.root_json+`} +
(default: `+Decoration.unspecified+`)

{empty} +


{empty} +

