= Stagg Specification

== Introduction

== Types

== Class definitions



=== Collection

[%hardbreaks]
{nbsp}—{nbsp} *objects*: list of <<Histogram>> or <<Ntuple>> or <<ParameterizedFunction>> or <<BinnedEvaluatedFunction>> or <<Collection>> +
(default: null/empty)
{nbsp}—{nbsp} *axis*: list of <<Axis>> (default: null/empty)
{nbsp}—{nbsp} *title*: str (default: null)
{nbsp}—{nbsp} *metadata*: <<Metadata>> (default: null)
{nbsp}—{nbsp} *decoration*: <<Decoration>> (default: null)
{nbsp}—{nbsp} *script*: str (default: null)

=== Histogram

[%hardbreaks]
{nbsp}—{nbsp}required  *axis*: list of <<Axis>> with length in [1, ∞)
{nbsp}—{nbsp}required  *counts*: <<UnweightedCounts>> or <<WeightedCounts>>
{nbsp}—{nbsp} *profile*: list of <<Profile>> (default: null/empty)
{nbsp}—{nbsp} *axis_covariances*: list of <<Covariance>> (default: null/empty)
{nbsp}—{nbsp} *profile_covariances*: list of <<Covariance>> (default: null/empty)
{nbsp}—{nbsp} *functions*: list of <<ParameterizedFunction>> or <<EvaluatedFunction>> (default: null/empty)
{nbsp}—{nbsp} *title*: str (default: null)
{nbsp}—{nbsp} *metadata*: <<Metadata>> (default: null)
{nbsp}—{nbsp} *decoration*: <<Decoration>> (default: null)
{nbsp}—{nbsp} *script*: str (default: null)

=== Axis

[%hardbreaks]
{nbsp}—{nbsp} *binning*: <<IntegerBinning>> or <<RegularBinning>> or <<HexagonalBinning>> or <<EdgesBinning>> or <<IrregularBinning>> or <<CategoryBinning>> or <<SparseRegularBinning>> or <<FractionBinning>> or <<PredicateBinning>> or <<VariationBinning>> +
(default: null)
{nbsp}—{nbsp} *expression*: str (default: null)
{nbsp}—{nbsp} *statistics*: <<Statistics>> (default: null)
{nbsp}—{nbsp} *title*: str (default: null)
{nbsp}—{nbsp} *metadata*: <<Metadata>> (default: null)
{nbsp}—{nbsp} *decoration*: <<Decoration>> (default: null)

=== IntegerBinning

[%hardbreaks]
{nbsp}—{nbsp}required  *min*: int in (‒∞, ∞)
{nbsp}—{nbsp}required  *max*: int in (‒∞, ∞)
{nbsp}—{nbsp} *loc_underflow*: one of {`+BinLocation.below3+`, `+BinLocation.below2+`, `+BinLocation.below1+`, `+BinLocation.nonexistent+`, `+BinLocation.above1+`, `+BinLocation.above2+`, `+BinLocation.above3+`} +
(default: `+BinLocation.nonexistent+`)
{nbsp}—{nbsp} *loc_overflow*: one of {`+BinLocation.below3+`, `+BinLocation.below2+`, `+BinLocation.below1+`, `+BinLocation.nonexistent+`, `+BinLocation.above1+`, `+BinLocation.above2+`, `+BinLocation.above3+`} +
(default: `+BinLocation.nonexistent+`)

=== RegularBinning

[%hardbreaks]
{nbsp}—{nbsp}required  *num*: int in [1, ∞)
{nbsp}—{nbsp}required  *interval*: <<RealInterval>>
{nbsp}—{nbsp} *overflow*: <<RealOverflow>> (default: null)
{nbsp}—{nbsp} *circular*: bool (default: false)

=== RealInterval

[%hardbreaks]
{nbsp}—{nbsp}required  *low*: float in [‒∞, ∞]
{nbsp}—{nbsp}required  *high*: float in [‒∞, ∞]
{nbsp}—{nbsp} *low_inclusive*: bool (default: true)
{nbsp}—{nbsp} *high_inclusive*: bool (default: false)

=== RealOverflow

[%hardbreaks]
{nbsp}—{nbsp} *loc_underflow*: one of {`+BinLocation.below3+`, `+BinLocation.below2+`, `+BinLocation.below1+`, `+BinLocation.nonexistent+`, `+BinLocation.above1+`, `+BinLocation.above2+`, `+BinLocation.above3+`} +
(default: `+BinLocation.nonexistent+`)
{nbsp}—{nbsp} *loc_overflow*: one of {`+BinLocation.below3+`, `+BinLocation.below2+`, `+BinLocation.below1+`, `+BinLocation.nonexistent+`, `+BinLocation.above1+`, `+BinLocation.above2+`, `+BinLocation.above3+`} +
(default: `+BinLocation.nonexistent+`)
{nbsp}—{nbsp} *loc_nanflow*: one of {`+BinLocation.below3+`, `+BinLocation.below2+`, `+BinLocation.below1+`, `+BinLocation.nonexistent+`, `+BinLocation.above1+`, `+BinLocation.above2+`, `+BinLocation.above3+`} +
(default: `+BinLocation.nonexistent+`)
{nbsp}—{nbsp} *minf_mapping*: one of {`+RealOverflow.missing+`, `+RealOverflow.in_underflow+`, `+RealOverflow.in_overflow+`, `+RealOverflow.in_nanflow+`} +
(default: `+RealOverflow.in_underflow+`)
{nbsp}—{nbsp} *pinf_mapping*: one of {`+RealOverflow.missing+`, `+RealOverflow.in_underflow+`, `+RealOverflow.in_overflow+`, `+RealOverflow.in_nanflow+`} +
(default: `+RealOverflow.in_overflow+`)
{nbsp}—{nbsp} *nan_mapping*: one of {`+RealOverflow.missing+`, `+RealOverflow.in_underflow+`, `+RealOverflow.in_overflow+`, `+RealOverflow.in_nanflow+`} +
(default: `+RealOverflow.in_nanflow+`)

=== HexagonalBinning

[%hardbreaks]
{nbsp}—{nbsp}required  *qmin*: int in (‒∞, ∞)
{nbsp}—{nbsp}required  *qmax*: int in (‒∞, ∞)
{nbsp}—{nbsp}required  *rmin*: int in (‒∞, ∞)
{nbsp}—{nbsp}required  *rmax*: int in (‒∞, ∞)
{nbsp}—{nbsp} *coordinates*: one of {`+HexagonalBinning.offset+`, `+HexagonalBinning.doubled_offset+`, `+HexagonalBinning.cube_xy+`, `+HexagonalBinning.cube_yz+`, `+HexagonalBinning.cube_xz+`} +
(default: `+HexagonalBinning.offset+`)
{nbsp}—{nbsp} *xorigin*: float in (‒∞, ∞) (default: 0.0)
{nbsp}—{nbsp} *yorigin*: float in (‒∞, ∞) (default: 0.0)
{nbsp}—{nbsp} *qangle*: float in [‒π/2, π/2] (default: 0.0)
{nbsp}—{nbsp} *qoverflow*: <<RealOverflow>> (default: null)
{nbsp}—{nbsp} *roverflow*: <<RealOverflow>> (default: null)

=== EdgesBinning

[%hardbreaks]
{nbsp}—{nbsp}required  *edges*: list of float with length in [1, ∞)
{nbsp}—{nbsp} *overflow*: <<RealOverflow>> (default: null)
{nbsp}—{nbsp} *low_inclusive*: bool (default: true)
{nbsp}—{nbsp} *high_inclusive*: bool (default: false)
{nbsp}—{nbsp} *circular*: bool (default: false)

=== IrregularBinning

[%hardbreaks]
{nbsp}—{nbsp}required  *intervals*: list of <<RealInterval>> with length in [1, ∞)
{nbsp}—{nbsp} *overflow*: <<RealOverflow>> (default: null)
{nbsp}—{nbsp} *overlapping_fill*: one of {`+IrregularBinning.undefined+`, `+IrregularBinning.all+`, `+IrregularBinning.first+`, `+IrregularBinning.last+`} +
(default: `+IrregularBinning.undefined+`)

=== CategoryBinning

[%hardbreaks]
{nbsp}—{nbsp}required  *categories*: list of str
{nbsp}—{nbsp} *loc_overflow*: one of {`+BinLocation.below3+`, `+BinLocation.below2+`, `+BinLocation.below1+`, `+BinLocation.nonexistent+`, `+BinLocation.above1+`, `+BinLocation.above2+`, `+BinLocation.above3+`} +
(default: `+BinLocation.nonexistent+`)

=== SparseRegularBinning

[%hardbreaks]
{nbsp}—{nbsp}required  *bins*: list of int
{nbsp}—{nbsp}required  *bin_width*: float in (0, ∞]
{nbsp}—{nbsp} *origin*: float in [‒∞, ∞] (default: 0.0)
{nbsp}—{nbsp} *overflow*: <<RealOverflow>> (default: null)
{nbsp}—{nbsp} *low_inclusive*: bool (default: true)
{nbsp}—{nbsp} *high_inclusive*: bool (default: false)
{nbsp}—{nbsp} *minbin*: int in [‒2⁶³, 2⁶³ ‒ 1] (default: ‒2⁶³)
{nbsp}—{nbsp} *maxbin*: int in [‒2⁶³, 2⁶³ ‒ 1] (default: 2⁶³ ‒ 1)

=== FractionBinning

[%hardbreaks]
{nbsp}—{nbsp} *layout*: one of {`+FractionBinning.passall+`, `+FractionBinning.failall+`, `+FractionBinning.passfail+`} +
(default: `+FractionBinning.passall+`)
{nbsp}—{nbsp} *layout_reversed*: bool (default: false)
{nbsp}—{nbsp} *error_method*: one of {`+FractionBinning.undefined+`, `+FractionBinning.normal+`, `+FractionBinning.clopper_pearson+`, `+FractionBinning.wilson+`, `+FractionBinning.agresti_coull+`, `+FractionBinning.feldman_cousins+`, `+FractionBinning.jeffrey+`, `+FractionBinning.bayesian_uniform+`} +
(default: `+FractionBinning.undefined+`)

=== PredicateBinning

[%hardbreaks]
{nbsp}—{nbsp}required  *predicates*: list of str with length in [1, ∞)
{nbsp}—{nbsp} *overlapping_fill*: one of {`+IrregularBinning.undefined+`, `+IrregularBinning.all+`, `+IrregularBinning.first+`, `+IrregularBinning.last+`} +
(default: `+IrregularBinning.undefined+`)

=== VariationBinning

[%hardbreaks]
{nbsp}—{nbsp}required  *variations*: list of <<Variation>> with length in [1, ∞)

=== Variation

[%hardbreaks]
{nbsp}—{nbsp}required  *assignments*: list of <<Assignment>>
{nbsp}—{nbsp} *systematic*: list of float (default: null/empty)
{nbsp}—{nbsp} *category_systematic*: list of str (default: null/empty)

=== Assignment

[%hardbreaks]
{nbsp}—{nbsp}required  *identifier*: unique str
{nbsp}—{nbsp}required  *expression*: str

=== UnweightedCounts

[%hardbreaks]
{nbsp}—{nbsp}required  *counts*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>>

=== WeightedCounts

[%hardbreaks]
{nbsp}—{nbsp}required  *sumw*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>>
{nbsp}—{nbsp} *sumw2*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>> +
(default: null)
{nbsp}—{nbsp} *unweighted*: <<UnweightedCounts>> (default: null)

=== InterpretedInlineBuffer

[%hardbreaks]
{nbsp}—{nbsp}required  *buffer*: buffer
{nbsp}—{nbsp} *filters*: list of {`+Buffer.none+`, `+Buffer.gzip+`, `+Buffer.lzma+`, `+Buffer.lz4+`} +
(default: null/empty)
{nbsp}—{nbsp} *postfilter_slice*: slice (start:stop:step) (default: null)
{nbsp}—{nbsp} *dtype*: one of {`+Interpretation.none+`, `+Interpretation.bool+`, `+Interpretation.int8+`, `+Interpretation.uint8+`, `+Interpretation.int16+`, `+Interpretation.uint16+`, `+Interpretation.int32+`, `+Interpretation.uint32+`, `+Interpretation.int64+`, `+Interpretation.uint64+`, `+Interpretation.float32+`, `+Interpretation.float64+`} +
(default: `+Interpretation.none+`)
{nbsp}—{nbsp} *endianness*: one of {`+Interpretation.little_endian+`, `+Interpretation.big_endian+`} +
(default: `+Interpretation.little_endian+`)
{nbsp}—{nbsp} *dimension_order*: one of {`+InterpretedBuffer.c_order+`, `+InterpretedBuffer.fortran+`} +
(default: `+InterpretedBuffer.c_order+`)

=== InterpretedInlineInt64Buffer

[%hardbreaks]
{nbsp}—{nbsp}required  *buffer*: buffer

=== InterpretedInlineFloat64Buffer

[%hardbreaks]
{nbsp}—{nbsp}required  *buffer*: buffer

=== InterpretedExternalBuffer

[%hardbreaks]
{nbsp}—{nbsp}required  *pointer*: int in [0, ∞)
{nbsp}—{nbsp}required  *numbytes*: int in [0, ∞)
{nbsp}—{nbsp} *external_source*: one of {`+ExternalBuffer.memory+`, `+ExternalBuffer.samefile+`, `+ExternalBuffer.file+`, `+ExternalBuffer.url+`} +
(default: `+ExternalBuffer.memory+`)
{nbsp}—{nbsp} *filters*: list of {`+Buffer.none+`, `+Buffer.gzip+`, `+Buffer.lzma+`, `+Buffer.lz4+`} +
(default: null/empty)
{nbsp}—{nbsp} *postfilter_slice*: slice (start:stop:step) (default: null)
{nbsp}—{nbsp} *dtype*: one of {`+Interpretation.none+`, `+Interpretation.bool+`, `+Interpretation.int8+`, `+Interpretation.uint8+`, `+Interpretation.int16+`, `+Interpretation.uint16+`, `+Interpretation.int32+`, `+Interpretation.uint32+`, `+Interpretation.int64+`, `+Interpretation.uint64+`, `+Interpretation.float32+`, `+Interpretation.float64+`} +
(default: `+Interpretation.none+`)
{nbsp}—{nbsp} *endianness*: one of {`+Interpretation.little_endian+`, `+Interpretation.big_endian+`} +
(default: `+Interpretation.little_endian+`)
{nbsp}—{nbsp} *dimension_order*: one of {`+InterpretedBuffer.c_order+`, `+InterpretedBuffer.fortran+`} +
(default: `+InterpretedBuffer.c_order+`)
{nbsp}—{nbsp} *location*: str (default: null)

=== Profile

[%hardbreaks]
{nbsp}—{nbsp}required  *expression*: str
{nbsp}—{nbsp}required  *statistics*: <<Statistics>>
{nbsp}—{nbsp} *title*: str (default: null)
{nbsp}—{nbsp} *metadata*: <<Metadata>> (default: null)
{nbsp}—{nbsp} *decoration*: <<Decoration>> (default: null)

=== Statistics

[%hardbreaks]
{nbsp}—{nbsp} *moments*: list of <<Moments>> (default: null/empty)
{nbsp}—{nbsp} *quantiles*: list of <<Quantiles>> (default: null/empty)
{nbsp}—{nbsp} *mode*: <<Modes>> (default: null)
{nbsp}—{nbsp} *min*: <<Extremes>> (default: null)
{nbsp}—{nbsp} *max*: <<Extremes>> (default: null)

=== Moments

[%hardbreaks]
{nbsp}—{nbsp}required  *sumwxn*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>>
{nbsp}—{nbsp}required  *n*: int in [‒128, 127]
{nbsp}—{nbsp} *weightpower*: int in [‒128, 127] (default: 0)
{nbsp}—{nbsp} *filter*: <<StatisticFilter>> (default: null)

=== Quantiles

[%hardbreaks]
{nbsp}—{nbsp}required  *values*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>>
{nbsp}—{nbsp}required  *p*: float in [0.0, 1.0] (default: 1/2)
{nbsp}—{nbsp} *weightpower*: int in [‒128, 127] (default: 0)
{nbsp}—{nbsp} *filter*: <<StatisticFilter>> (default: null)

=== Modes

[%hardbreaks]
{nbsp}—{nbsp}required  *values*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>>
{nbsp}—{nbsp} *filter*: <<StatisticFilter>> (default: null)

=== Extremes

[%hardbreaks]
{nbsp}—{nbsp}required  *values*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>>
{nbsp}—{nbsp} *filter*: <<StatisticFilter>> (default: null)

=== StatisticFilter

[%hardbreaks]
{nbsp}—{nbsp} *min*: float in [‒∞, ∞] (default: ‒∞)
{nbsp}—{nbsp} *max*: float in [‒∞, ∞] (default: ∞)
{nbsp}—{nbsp} *excludes_minf*: bool (default: false)
{nbsp}—{nbsp} *excludes_pinf*: bool (default: false)
{nbsp}—{nbsp} *excludes_nan*: bool (default: false)

=== Covariance

[%hardbreaks]
{nbsp}—{nbsp}required  *xindex*: int in [0, ∞)
{nbsp}—{nbsp}required  *yindex*: int in [0, ∞)
{nbsp}—{nbsp}required  *sumwxy*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>>
{nbsp}—{nbsp} *weightpower*: int in [‒128, 127] (default: 0)
{nbsp}—{nbsp} *filter*: <<StatisticFilter>> (default: null)

=== ParameterizedFunction

[%hardbreaks]
{nbsp}—{nbsp}required  *expression*: str
{nbsp}—{nbsp} *parameters*: list of <<Parameter>> (default: null/empty)
{nbsp}—{nbsp} *title*: str (default: null)
{nbsp}—{nbsp} *metadata*: <<Metadata>> (default: null)
{nbsp}—{nbsp} *decoration*: <<Decoration>> (default: null)
{nbsp}—{nbsp} *script*: str (default: null)

=== Parameter

[%hardbreaks]
{nbsp}—{nbsp}required  *identifier*: unique str
{nbsp}—{nbsp}required  *values*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>>

=== EvaluatedFunction

[%hardbreaks]
{nbsp}—{nbsp}required  *values*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>>
{nbsp}—{nbsp} *derivatives*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>> +
(default: null)
{nbsp}—{nbsp} *errors*: list of <<Quantiles>> (default: null/empty)
{nbsp}—{nbsp} *title*: str (default: null)
{nbsp}—{nbsp} *metadata*: <<Metadata>> (default: null)
{nbsp}—{nbsp} *decoration*: <<Decoration>> (default: null)
{nbsp}—{nbsp} *script*: str (default: null)

=== BinnedEvaluatedFunction

[%hardbreaks]
{nbsp}—{nbsp}required  *axis*: list of <<Axis>> with length in [1, ∞)
{nbsp}—{nbsp}required  *values*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>>
{nbsp}—{nbsp} *derivatives*: <<InterpretedInlineBuffer>> or <<InterpretedInlineInt64Buffer>> or <<InterpretedInlineFloat64Buffer>> or <<InterpretedExternalBuffer>> +
(default: null)
{nbsp}—{nbsp} *errors*: list of <<Quantiles>> (default: null/empty)
{nbsp}—{nbsp} *title*: str (default: null)
{nbsp}—{nbsp} *metadata*: <<Metadata>> (default: null)
{nbsp}—{nbsp} *decoration*: <<Decoration>> (default: null)
{nbsp}—{nbsp} *script*: str (default: null)

=== Ntuple

[%hardbreaks]
{nbsp}—{nbsp}required  *columns*: list of <<Column>> with length in [1, ∞)
{nbsp}—{nbsp}required  *instances*: list of <<NtupleInstance>> with length in [1, ∞)
{nbsp}—{nbsp} *column_statistics*: list of <<Statistics>> (default: null/empty)
{nbsp}—{nbsp} *column_covariances*: list of <<Covariance>> (default: null/empty)
{nbsp}—{nbsp} *functions*: list of <<ParameterizedFunction>> or <<BinnedEvaluatedFunction>> (default: null/empty)
{nbsp}—{nbsp} *title*: str (default: null)
{nbsp}—{nbsp} *metadata*: <<Metadata>> (default: null)
{nbsp}—{nbsp} *decoration*: <<Decoration>> (default: null)
{nbsp}—{nbsp} *script*: str (default: null)

=== Column

[%hardbreaks]
{nbsp}—{nbsp}required  *identifier*: unique str
{nbsp}—{nbsp}required  *dtype*: one of {`+Interpretation.none+`, `+Interpretation.bool+`, `+Interpretation.int8+`, `+Interpretation.uint8+`, `+Interpretation.int16+`, `+Interpretation.uint16+`, `+Interpretation.int32+`, `+Interpretation.uint32+`, `+Interpretation.int64+`, `+Interpretation.uint64+`, `+Interpretation.float32+`, `+Interpretation.float64+`}
{nbsp}—{nbsp} *endianness*: one of {`+Interpretation.little_endian+`, `+Interpretation.big_endian+`} +
(default: `+Interpretation.little_endian+`)
{nbsp}—{nbsp} *filters*: list of {`+Buffer.none+`, `+Buffer.gzip+`, `+Buffer.lzma+`, `+Buffer.lz4+`} +
(default: null/empty)
{nbsp}—{nbsp} *postfilter_slice*: slice (start:stop:step) (default: null)
{nbsp}—{nbsp} *title*: str (default: null)
{nbsp}—{nbsp} *metadata*: <<Metadata>> (default: null)
{nbsp}—{nbsp} *decoration*: <<Decoration>> (default: null)

=== NtupleInstance

[%hardbreaks]
{nbsp}—{nbsp}required  *chunks*: list of <<Chunk>>
{nbsp}—{nbsp} *chunk_offsets*: list of int (default: null/empty)

=== Chunk

[%hardbreaks]
{nbsp}—{nbsp}required  *column_chunks*: list of <<ColumnChunk>>
{nbsp}—{nbsp} *metadata*: <<Metadata>> (default: null)

=== ColumnChunk

[%hardbreaks]
{nbsp}—{nbsp}required  *pages*: list of <<Page>>
{nbsp}—{nbsp}required  *page_offsets*: list of int with length in [1, ∞)
{nbsp}—{nbsp} *page_min*: list of <<Extremes>> (default: null/empty)
{nbsp}—{nbsp} *page_max*: list of <<Extremes>> (default: null/empty)

=== Page

[%hardbreaks]
{nbsp}—{nbsp}required  *buffer*: <<RawInlineBuffer>> or <<RawExternalBuffer>>

=== RawInlineBuffer

[%hardbreaks]
{nbsp}—{nbsp}required  *buffer*: buffer

=== RawExternalBuffer

[%hardbreaks]
{nbsp}—{nbsp}required  *pointer*: int in [0, ∞)
{nbsp}—{nbsp}required  *numbytes*: int in [0, ∞)
{nbsp}—{nbsp} *external_source*: one of {`+ExternalBuffer.memory+`, `+ExternalBuffer.samefile+`, `+ExternalBuffer.file+`, `+ExternalBuffer.url+`} +
(default: `+ExternalBuffer.memory+`)

=== Metadata

[%hardbreaks]
{nbsp}—{nbsp}required  *data*: str
{nbsp}—{nbsp}required  *language*: one of {`+Metadata.unspecified+`, `+Metadata.json+`} (default: `+Metadata.unspecified+`)

=== Decoration

[%hardbreaks]
{nbsp}—{nbsp}required  *data*: str
{nbsp}—{nbsp}required  *language*: one of {`+Decoration.unspecified+`, `+Decoration.css+`, `+Decoration.vega+`, `+Decoration.root_json+`} +
(default: `+Decoration.unspecified+`)
