# automatically generated by the FlatBuffers compiler, do not modify

# namespace: aghast_generated

import flatbuffers


class Assignment(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAsAssignment(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Assignment()
        x.Init(buf, n + offset)
        return x

    # Assignment
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Assignment
    def Identifier(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Assignment
    def Expression(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None


def AssignmentStart(builder):
    builder.StartObject(2)


def AssignmentAddIdentifier(builder, identifier):
    builder.PrependUOffsetTRelativeSlot(
        0, flatbuffers.number_types.UOffsetTFlags.py_type(identifier), 0
    )


def AssignmentAddExpression(builder, expression):
    builder.PrependUOffsetTRelativeSlot(
        1, flatbuffers.number_types.UOffsetTFlags.py_type(expression), 0
    )


def AssignmentEnd(builder):
    return builder.EndObject()
