# automatically generated by the FlatBuffers compiler, do not modify

# namespace: aghast_generated

import flatbuffers


class BinnedEvaluatedFunction(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAsBinnedEvaluatedFunction(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BinnedEvaluatedFunction()
        x.Init(buf, n + offset)
        return x

    # BinnedEvaluatedFunction
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BinnedEvaluatedFunction
    def Axis(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .Axis import Axis

            obj = Axis()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # BinnedEvaluatedFunction
    def AxisLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # BinnedEvaluatedFunction
    def Data(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .EvaluatedFunction import EvaluatedFunction

            obj = EvaluatedFunction()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None


def BinnedEvaluatedFunctionStart(builder):
    builder.StartObject(2)


def BinnedEvaluatedFunctionAddAxis(builder, axis):
    builder.PrependUOffsetTRelativeSlot(
        0, flatbuffers.number_types.UOffsetTFlags.py_type(axis), 0
    )


def BinnedEvaluatedFunctionStartAxisVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)


def BinnedEvaluatedFunctionAddData(builder, data):
    builder.PrependUOffsetTRelativeSlot(
        1, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0
    )


def BinnedEvaluatedFunctionEnd(builder):
    return builder.EndObject()
