# automatically generated by the FlatBuffers compiler, do not modify

# namespace: aghast_generated

import flatbuffers


class Extremes(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAsExtremes(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Extremes()
        x.Init(buf, n + offset)
        return x

    # Extremes
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Extremes
    def ValuesType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Extremes
    def Values(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table

            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

    # Extremes
    def Filter(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = o + self._tab.Pos
            from .StatisticFilter import StatisticFilter

            obj = StatisticFilter()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None


def ExtremesStart(builder):
    builder.StartObject(3)


def ExtremesAddValuesType(builder, valuesType):
    builder.PrependUint8Slot(0, valuesType, 0)


def ExtremesAddValues(builder, values):
    builder.PrependUOffsetTRelativeSlot(
        1, flatbuffers.number_types.UOffsetTFlags.py_type(values), 0
    )


def ExtremesAddFilter(builder, filter):
    builder.PrependStructSlot(
        2, flatbuffers.number_types.UOffsetTFlags.py_type(filter), 0
    )


def ExtremesEnd(builder):
    return builder.EndObject()
