# automatically generated by the FlatBuffers compiler, do not modify

# namespace: aghast_generated

import flatbuffers

class FunctionObject(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsFunctionObject(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FunctionObject()
        x.Init(buf, n + offset)
        return x

    # FunctionObject
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FunctionObject
    def DataType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # FunctionObject
    def Data(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def FunctionObjectStart(builder): builder.StartObject(2)
def FunctionObjectAddDataType(builder, dataType): builder.PrependUint8Slot(0, dataType, 0)
def FunctionObjectAddData(builder, data): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)
def FunctionObjectEnd(builder): return builder.EndObject()
