# automatically generated by the FlatBuffers compiler, do not modify

# namespace: aghast_generated

import flatbuffers

class InterpretedInlineInt64Buffer(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsInterpretedInlineInt64Buffer(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = InterpretedInlineInt64Buffer()
        x.Init(buf, n + offset)
        return x

    # InterpretedInlineInt64Buffer
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # InterpretedInlineInt64Buffer
    def Buffer(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # InterpretedInlineInt64Buffer
    def BufferAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # InterpretedInlineInt64Buffer
    def BufferLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def InterpretedInlineInt64BufferStart(builder): builder.StartObject(1)
def InterpretedInlineInt64BufferAddBuffer(builder, buffer): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(buffer), 0)
def InterpretedInlineInt64BufferStartBufferVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def InterpretedInlineInt64BufferEnd(builder): return builder.EndObject()
