# automatically generated by the FlatBuffers compiler, do not modify

# namespace: aghast_generated

import flatbuffers

# ///////////////////////////////////////////////// ntuple
class Page(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAsPage(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Page()
        x.Init(buf, n + offset)
        return x

    # Page
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Page
    def BufferType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Page
    def Buffer(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table

            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None


def PageStart(builder):
    builder.StartObject(2)


def PageAddBufferType(builder, bufferType):
    builder.PrependUint8Slot(0, bufferType, 0)


def PageAddBuffer(builder, buffer):
    builder.PrependUOffsetTRelativeSlot(
        1, flatbuffers.number_types.UOffsetTFlags.py_type(buffer), 0
    )


def PageEnd(builder):
    return builder.EndObject()
