# automatically generated by the FlatBuffers compiler, do not modify

# namespace: aghast_generated

import flatbuffers

# ///////////////////////////////////////////////// distributions
class UnweightedCounts(object):
    __slots__ = ["_tab"]

    @classmethod
    def GetRootAsUnweightedCounts(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UnweightedCounts()
        x.Init(buf, n + offset)
        return x

    # UnweightedCounts
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UnweightedCounts
    def CountsType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # UnweightedCounts
    def Counts(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table

            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None


def UnweightedCountsStart(builder):
    builder.StartObject(2)


def UnweightedCountsAddCountsType(builder, countsType):
    builder.PrependUint8Slot(0, countsType, 0)


def UnweightedCountsAddCounts(builder, counts):
    builder.PrependUOffsetTRelativeSlot(
        1, flatbuffers.number_types.UOffsetTFlags.py_type(counts), 0
    )


def UnweightedCountsEnd(builder):
    return builder.EndObject()
